---
name: moodle

releases:
- name: buildstack
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: moodle
  azs:
  - z1
  instances: 1
  jobs:
  - name: moodle
    release: buildstack
  vm_type: m3.medium
  stemcell: default
  networks:
  - name: default
